In [1]:
import requests
import sqlite3
import pandas as pd
from IPython.display import display

API_URL = "https://openlibrary.org/search.json"
DB_NAME = "books.db"
BOOK_LIMIT = 100

In [2]:
params = {
    "title": "The Hobbit",
    "limit": BOOK_LIMIT
}

response = requests.get(API_URL, params=params, timeout=20)
response.raise_for_status()

data = response.json()
books = data.get("docs", [])

print("Total matching records reported by API:", data.get("numFound"))
print("Records fetched in this request:", len(books))

Total matching records reported by API: 224
Records fetched in this request: 100

In [3]:
if books:
    display(pd.json_normalize(books[:1]).T)
else:
    print("No records returned.")

                                                                      0
author_key                                                   [OL26320A]
author_name                                            [J.R.R. Tolkien]
cover_edition_key                                           OL51711263M
cover_height                                                        611
cover_i                                                        14627509
cover_width                                                         368
ebook_access                                                 borrowable
edition_count                                                       482
first_publish_year                                                 1937
has_fulltext                                                       True
ia                    [hobbitortherebac00tolk_2, annotatedhobbith00t...
ia_collection         [JaiGyan, ServantsOfKnowledge-Print, americana...
key                                                     /works/OL27482W
language              [ang, heb, ukr, lat, lez, fin, fre, cor, dut, ...
lending_edition_s                                           OL51709286M
lending_identifier_s                           hobbitortherebac00tolk_2
public_scan_b                                                     False
title                                                        The Hobbit

In [4]:
book_records = []

for book in books:
    title = book.get("title")
    authors = book.get("author_name") or []
    year = book.get("first_publish_year")
    record_id = book.get("key")

    if not title or not record_id:
        continue

    book_records.append({
        "record_id": record_id.strip(),
        "title": title.strip(),
        "author": ", ".join(authors) if authors else "Unknown",
        "publication_year": year
    })

books_df = pd.DataFrame(book_records)

books_df = books_df.drop_duplicates(subset="record_id")
books_df = books_df.sort_values("title", na_position="last").reset_index(drop=True)


print("Cleaned records:", len(books_df))

Cleaned records: 100

In [5]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 60)

display(books_df)

,record_id,title,author,publication_year
0,/works/OL20493903W,A Brief History of the Hobbit,John D. Rateliff,2018.0
1,/works/OL16477282W,A reader's companion to The hobbit and the lord of the r...,"Joseph Mathewson, Isaac Asimov, C. S. Lewis, W. H. Auden...",1995.0
2,/works/OL28275670W,A-Z of JRR Tolkien's the Hobbit,Sarah Oliver,2012.0
3,/works/OL21034216W,Art of the Hobbit,"J.R.R. Tolkien, Christina Scull, Wayne G. Hammond",2011.0
4,/works/OL16637291W,Exploring J.R.R. Tolkien's The hobbit,Corey Olsen,2012.0
5,/works/OL25117415W,Finding God in the Hobbit,Jim Ware,2006.0
6,/works/OL5753335W,Finding God in the Hobbit,Jim Ware,2006.0
7,/works/OL34051627W,History of the Hobbit,J.R.R. Tolkien,2023.0
8,/works/OL21271107W,Hobbit : the Desolation of Smaug Chronicles,Weta,2013.0
9,/works/OL35889944W,Hobbit Quizzes : the Hobbit Facts and Trivia,Taulbee CHRISTEN,2021.0
10,/works/OL21518798W,Hobbit The Desolation of Smaug,Brian Sibley,2012.0
11,/works/OL28358521W,J. R. R. Tolkien's the Hobbit,Robert T. Tally,2022.0
12,/works/OL16059606W,J.R.R. Tolkien's The hobbit,Patsey Gray,1968.0
13,/works/OL15942009W,J.R.R. Tolkien's The hobbit,Harold Bloom,2011.0
14,/works/OL16703020W,"Nittaewo, the hobbits of Sri Lanka",Pradeep A. Jayatunga,2010.0
15,/works/OL27496W,Novels (Fellowship of the Ring / Hobbit),J.R.R. Tolkien,1954.0
16,/works/OL16704560W,On the shoulders of hobbits,Louis Markos,2012.0
17,/works/OL14933471W,Poems from The hobbit,J.R.R. Tolkien,1999.0
18,/works/OL19649378W,Smaug: Unleashing the Dragon (The Hobbit: The Desolation...,Daniel Falconer,2014.0
19,/works/OL38298289W,Summary of the Hobbit,Whizbooks,2019.0
20,/works/OL8144078W,The American Hobbit,G. Ellis Wheeler,2001.0
21,/works/OL17454326W,The Christian World Of The Hobbit,Devin Brown,2012.0
22,/works/OL8571577W,The History of the Hobbit,John D. Rateliff,2007.0
23,/works/OL8571576W,The History of the Hobbit,John D. Rateliff,2007.0
24,/works/OL19659525W,The Hobbit,Unknown,1975.0
25,/works/OL20326024W,The Hobbit,Natasha Hughes,2014.0
26,/works/OL19659522W,The Hobbit,Unknown,1975.0
27,/works/OL17863441W,The Hobbit,"Jeff Barton, Mario De Govia",2003.0
28,/works/OL8946327W,The Hobbit,Mary B. Collins,2002.0
29,/works/OL45346371W,The Hobbit,J.R.R. Tolkien,2026.0
30,/works/OL31352578W,The Hobbit,Unknown,NaN
31,/works/OL13253846M,The Hobbit,Unknown,1986.0
32,/works/OL7106240W,The Hobbit,James S. Scott,2000.0
33,/works/OL19659523W,The Hobbit,Unknown,1975.0
34,/works/OL27482W,The Hobbit,J.R.R. Tolkien,1937.0
35,/works/OL14926093W,The Hobbit,"Patrick Gardner, Brian Philips",2002.0
36,/works/OL19659526W,The Hobbit,Unknown,1975.0
37,/works/OL28617330W,The Hobbit,SparkNotes,2014.0
38,/works/OL219602W,The Hobbit,"Charles Dixon, Sean Deming, J.R.R. Tolkien",1990.0
39,/works/OL4699021W,The Hobbit,Mary Elizabeth,1998.0
40,/works/OL33968596W,The Hobbit,Ian McKellen,2013.0
41,/works/OL19622663W,The Hobbit,Charles Dixon,1990.0
42,/works/OL36767804W,The Hobbit,Unknown,1928.0
43,/works/OL31640402W,The Hobbit,Howard Shore,2013.0
44,/works/OL20683713W,The Hobbit,Jude Fisher,2012.0
45,/works/OL14926019W,The Hobbit & The Lord of the Rings [collection/set],J.R.R. Tolkien,1979.0
46,/works/OL26532418W,The Hobbit -- An Unexpected Journey,"Howard Shore, Dan Coates",2013.0
47,/works/OL14933367W,The Hobbit / Lord of the Rings / Silmarillion,J.R.R. Tolkien,2004.0
48,/works/OL20319928W,The Hobbit : The Battle of the Five Armies Chronicles,Weta,2014.0
49,/works/OL20365605W,The Hobbit : The Desolation of Smaug,Brian Sibley,2013.0
50,/works/OL24195803W,The Hobbit : the battle of the five armies,Paddy Kempsall,2014.0
51,/works/OL17566361W,The Hobbit An Unexpected Journey,Daniel Falconer,2012.0
52,/works/OL17448738W,The Hobbit An Unexpected Journey Chronicles Art Design,Weta Workshop,2012.0
53,/works/OL17414656W,The Hobbit Chronicles An Unexpected Journey,Daniel Falconer,2013.0
54,/works/OL9896426W,The Hobbit Novel Guide,Shan Gillard,1900.0
55,/works/OL8961249W,The Hobbit Study Guide,Michael Poteet,2000.0
56,/works/OL17406449W,The Hobbit The Desolation Of Smaug Art Design,Daniel Falconer,2013.0
57,/works/OL22360658W,The Hobbit Trilogy Location Guidebook,Ian Brodie,2014.0
58,/works/OL23201024W,The Hobbit and History,"Janice Liedl, Nancy Ruth Reagin",2014.0
59,/works/OL16557942W,The Hobbit and philosophy,"Gregory Bassham, Eric Bronson",2012.0
60,/works/OL5756550W,The Hobbit by J.R.R. Tolkien,"Reid, Paul.",1998.0
61,/works/OL18169548W,The Hobbit companion,David Day,1997.0
62,/works/OL24172914W,The Hobbit companion,David Day,1997.0
63,/works/OL2994831W,The Hobbit companion,David Day,2000.0
64,/works/OL19989843W,The Hobbit party,Jonathan Witt,2014.0
65,/works/OL12002307W,The Hobbit trap,Maciej Henneberg,2008.0
66,/works/OL14933368W,"The Hobbit, 1 Act",Edward Mast,1996.0
67,/works/OL19961152W,"The Hobbit, an unexpected journey",Brian Sibley,2012.0
68,/works/OL9839100W,"The Hobbit, by J.R.R. Tolkien",Vicki Macfarlane,1991.0
69,/works/OL34678626W,The Hobbit.,Unknown,NaN
70,/works/OL14933388W,The Hobbit. 2/?,J.R.R. Tolkien,1984.0
71,/works/OL17838892W,The Hobbit. An Unexpected Journey. Activity Book,Warner Bros Entertainment,2012.0
72,/works/OL11222974M,The Hobbit/Audio Cassettes,Unknown,1985.0
73,/works/OL24269838W,The Hobbit: an unexpected journey,Paddy Kempshall,2012.0
74,/works/OL20100930W,The Hobbit: the Battle of the Five Armies - Official Mov...,Brian Sibley,2014.0
75,/works/OL17888352W,The Hobbits,Lynnette R. Porter,2012.0
76,/works/OL18146934W,The Lord of the Rings / The Hobbit,Coles Editorial Board,1979.0
77,/works/OL14933384W,"The Lord of the Rings, The Hobbit",Coles Editorial Board,2003.0
78,/works/OL17438903W,The Riddles Of The Hobbit,Adam Roberts,2013.0
79,/works/OL23899079W,The Tengwar Hobbit,J.R.R. Tolkien,2020.0
80,/works/OL17554712W,The Unofficial Hobbit Handbook,Jeff Gerke,2012.0
81,/works/OL38341864W,The Wisdom of Hobbits,"Matthew J. Distefano, Michael Machuga",2023.0
82,/works/OL22645426W,The World of Hobbits,Paddy Kempshall,2012.0
83,/works/OL5964608W,The discovery of the hobbit,"M. J. Morwood, Mike Morwood, Penny Van Oosterzee",2006.0
84,/works/OL24180247W,The hobbit,Patty Kempshall,2012.0
85,/works/OL5964807W,The hobbit,Jeff Barton,2003.0
86,/works/OL19708448W,The hobbit : the desolation of Smaug,Howard Shore,2013.0
87,/works/OL8326333W,The hobbit the musical,"Ruth Perry, J.R.R. Tolkien",1972.0
88,/works/OL24269837W,"The hobbit, J.R.R. Tolkien",Spark Publishing,2007.0
89,/works/OL20984479W,"The hobbit, the desolation of Smaug movie storybook",Warner Brothers,2013.0
90,/works/OL5279260W,The individuated hobbit,Timothy R. O'Neill,1979.0
91,/works/OL16769389W,The spiritual world of The hobbit,"James S. Bell, James Stuart Bell, Sam O'Neal",2012.0
92,/works/OL16704968W,The unofficial Hobbit trivia challenge,Nick Hurwitch,2012.0
93,/works/OL10367789W,Tolkien's The Lord of the Rings and The hobbit,Gene B. Hardy,1977.0
94,/works/OL40243911W,Trivia : the Hobbit,Trivion Books,2016.0
95,/works/OL3473990W,Twayne's Masterwork Studies - The Hobbit. A Journey to M...,William H. Green,1994.0
96,/works/OL35867918W,Wholesome Meals from the Hobbit,Johny Bomer,2021.0
97,/works/OL30010020W,William Shakespeare's the Hobbit,Mike Rogers,2019.0
98,/works/OL42983604W,the annotated hobbit,douglas a. anderson,1966.0
99,/works/OL34160641W,𝕋𝕙𝕖 ℍ𝕠𝕓𝕓𝕚𝕥 Photobook,"Bradford, Rhona Bradford",2022.0

In [6]:
with sqlite3.connect(DB_NAME) as conn:
    conn.execute("""
        CREATE TABLE IF NOT EXISTS books (
            record_id TEXT PRIMARY KEY,
            title TEXT NOT NULL,
            author TEXT,
            publication_year INTEGER
        )
    """)

print("SQLite table is ready.")

SQLite table is ready.

In [7]:
with sqlite3.connect(DB_NAME) as conn:
    for _, row in books_df.iterrows():
        conn.execute("""
            INSERT OR IGNORE INTO books
            (record_id, title, author, publication_year)
            VALUES (?, ?, ?, ?)
        """, (
            row["record_id"],
            row["title"],
            row["author"],
            row["publication_year"]
        ))

print("Cleaned records saved successfully.")

Cleaned records saved successfully.

In [8]:
with sqlite3.connect(DB_NAME) as conn:
    stored_df = pd.read_sql_query("""
        SELECT record_id, title, author, publication_year
        FROM books
        ORDER BY title COLLATE NOCASE
    """, conn)

display(stored_df)
print("Total records stored:", len(stored_df))

,record_id,title,author,publication_year
0,/works/OL20493903W,A Brief History of the Hobbit,John D. Rateliff,2018.0
1,/works/OL16477282W,A reader's companion to The hobbit and the lord of the r...,"Joseph Mathewson, Isaac Asimov, C. S. Lewis, W. H. Auden...",1995.0
2,/works/OL28275670W,A-Z of JRR Tolkien's the Hobbit,Sarah Oliver,2012.0
3,/works/OL21034216W,Art of the Hobbit,"J.R.R. Tolkien, Christina Scull, Wayne G. Hammond",2011.0
4,/works/OL16637291W,Exploring J.R.R. Tolkien's The hobbit,Corey Olsen,2012.0
5,/works/OL25117415W,Finding God in the Hobbit,Jim Ware,2006.0
6,/works/OL5753335W,Finding God in the Hobbit,Jim Ware,2006.0
7,/works/OL34051627W,History of the Hobbit,J.R.R. Tolkien,2023.0
8,/works/OL21271107W,Hobbit : the Desolation of Smaug Chronicles,Weta,2013.0
9,/works/OL35889944W,Hobbit Quizzes : the Hobbit Facts and Trivia,Taulbee CHRISTEN,2021.0
10,/works/OL21518798W,Hobbit The Desolation of Smaug,Brian Sibley,2012.0
11,/works/OL28358521W,J. R. R. Tolkien's the Hobbit,Robert T. Tally,2022.0
12,/works/OL16059606W,J.R.R. Tolkien's The hobbit,Patsey Gray,1968.0
13,/works/OL15942009W,J.R.R. Tolkien's The hobbit,Harold Bloom,2011.0
14,/works/OL16703020W,"Nittaewo, the hobbits of Sri Lanka",Pradeep A. Jayatunga,2010.0
15,/works/OL27496W,Novels (Fellowship of the Ring / Hobbit),J.R.R. Tolkien,1954.0
16,/works/OL16704560W,On the shoulders of hobbits,Louis Markos,2012.0
17,/works/OL14933471W,Poems from The hobbit,J.R.R. Tolkien,1999.0
18,/works/OL19649378W,Smaug: Unleashing the Dragon (The Hobbit: The Desolation...,Daniel Falconer,2014.0
19,/works/OL38298289W,Summary of the Hobbit,Whizbooks,2019.0
20,/works/OL8144078W,The American Hobbit,G. Ellis Wheeler,2001.0
21,/works/OL42983604W,the annotated hobbit,douglas a. anderson,1966.0
22,/works/OL17454326W,The Christian World Of The Hobbit,Devin Brown,2012.0
23,/works/OL5964608W,The discovery of the hobbit,"M. J. Morwood, Mike Morwood, Penny Van Oosterzee",2006.0
24,/works/OL8571577W,The History of the Hobbit,John D. Rateliff,2007.0
25,/works/OL8571576W,The History of the Hobbit,John D. Rateliff,2007.0
26,/works/OL19659525W,The Hobbit,Unknown,1975.0
27,/works/OL20326024W,The Hobbit,Natasha Hughes,2014.0
28,/works/OL19659522W,The Hobbit,Unknown,1975.0
29,/works/OL17863441W,The Hobbit,"Jeff Barton, Mario De Govia",2003.0
30,/works/OL8946327W,The Hobbit,Mary B. Collins,2002.0
31,/works/OL45346371W,The Hobbit,J.R.R. Tolkien,2026.0
32,/works/OL31352578W,The Hobbit,Unknown,NaN
33,/works/OL13253846M,The Hobbit,Unknown,1986.0
34,/works/OL7106240W,The Hobbit,James S. Scott,2000.0
35,/works/OL19659523W,The Hobbit,Unknown,1975.0
36,/works/OL27482W,The Hobbit,J.R.R. Tolkien,1937.0
37,/works/OL14926093W,The Hobbit,"Patrick Gardner, Brian Philips",2002.0
38,/works/OL19659526W,The Hobbit,Unknown,1975.0
39,/works/OL28617330W,The Hobbit,SparkNotes,2014.0
40,/works/OL219602W,The Hobbit,"Charles Dixon, Sean Deming, J.R.R. Tolkien",1990.0
41,/works/OL4699021W,The Hobbit,Mary Elizabeth,1998.0
42,/works/OL33968596W,The Hobbit,Ian McKellen,2013.0
43,/works/OL19622663W,The Hobbit,Charles Dixon,1990.0
44,/works/OL36767804W,The Hobbit,Unknown,1928.0
45,/works/OL31640402W,The Hobbit,Howard Shore,2013.0
46,/works/OL20683713W,The Hobbit,Jude Fisher,2012.0
47,/works/OL24180247W,The hobbit,Patty Kempshall,2012.0
48,/works/OL5964807W,The hobbit,Jeff Barton,2003.0
49,/works/OL14926019W,The Hobbit & The Lord of the Rings [collection/set],J.R.R. Tolkien,1979.0
50,/works/OL26532418W,The Hobbit -- An Unexpected Journey,"Howard Shore, Dan Coates",2013.0
51,/works/OL14933367W,The Hobbit / Lord of the Rings / Silmarillion,J.R.R. Tolkien,2004.0
52,/works/OL24195803W,The Hobbit : the battle of the five armies,Paddy Kempsall,2014.0
53,/works/OL20319928W,The Hobbit : The Battle of the Five Armies Chronicles,Weta,2014.0
54,/works/OL20365605W,The Hobbit : The Desolation of Smaug,Brian Sibley,2013.0
55,/works/OL19708448W,The hobbit : the desolation of Smaug,Howard Shore,2013.0
56,/works/OL17566361W,The Hobbit An Unexpected Journey,Daniel Falconer,2012.0
57,/works/OL17448738W,The Hobbit An Unexpected Journey Chronicles Art Design,Weta Workshop,2012.0
58,/works/OL23201024W,The Hobbit and History,"Janice Liedl, Nancy Ruth Reagin",2014.0
59,/works/OL16557942W,The Hobbit and philosophy,"Gregory Bassham, Eric Bronson",2012.0
60,/works/OL5756550W,The Hobbit by J.R.R. Tolkien,"Reid, Paul.",1998.0
61,/works/OL17414656W,The Hobbit Chronicles An Unexpected Journey,Daniel Falconer,2013.0
62,/works/OL18169548W,The Hobbit companion,David Day,1997.0
63,/works/OL24172914W,The Hobbit companion,David Day,1997.0
64,/works/OL2994831W,The Hobbit companion,David Day,2000.0
65,/works/OL9896426W,The Hobbit Novel Guide,Shan Gillard,1900.0
66,/works/OL19989843W,The Hobbit party,Jonathan Witt,2014.0
67,/works/OL8961249W,The Hobbit Study Guide,Michael Poteet,2000.0
68,/works/OL17406449W,The Hobbit The Desolation Of Smaug Art Design,Daniel Falconer,2013.0
69,/works/OL8326333W,The hobbit the musical,"Ruth Perry, J.R.R. Tolkien",1972.0
70,/works/OL12002307W,The Hobbit trap,Maciej Henneberg,2008.0
71,/works/OL22360658W,The Hobbit Trilogy Location Guidebook,Ian Brodie,2014.0
72,/works/OL14933368W,"The Hobbit, 1 Act",Edward Mast,1996.0
73,/works/OL19961152W,"The Hobbit, an unexpected journey",Brian Sibley,2012.0
74,/works/OL9839100W,"The Hobbit, by J.R.R. Tolkien",Vicki Macfarlane,1991.0
75,/works/OL24269837W,"The hobbit, J.R.R. Tolkien",Spark Publishing,2007.0
76,/works/OL20984479W,"The hobbit, the desolation of Smaug movie storybook",Warner Brothers,2013.0
77,/works/OL34678626W,The Hobbit.,Unknown,NaN
78,/works/OL14933388W,The Hobbit. 2/?,J.R.R. Tolkien,1984.0
79,/works/OL17838892W,The Hobbit. An Unexpected Journey. Activity Book,Warner Bros Entertainment,2012.0
80,/works/OL11222974M,The Hobbit/Audio Cassettes,Unknown,1985.0
81,/works/OL24269838W,The Hobbit: an unexpected journey,Paddy Kempshall,2012.0
82,/works/OL20100930W,The Hobbit: the Battle of the Five Armies - Official Mov...,Brian Sibley,2014.0
83,/works/OL17888352W,The Hobbits,Lynnette R. Porter,2012.0
84,/works/OL5279260W,The individuated hobbit,Timothy R. O'Neill,1979.0
85,/works/OL18146934W,The Lord of the Rings / The Hobbit,Coles Editorial Board,1979.0
86,/works/OL14933384W,"The Lord of the Rings, The Hobbit",Coles Editorial Board,2003.0
87,/works/OL17438903W,The Riddles Of The Hobbit,Adam Roberts,2013.0
88,/works/OL16769389W,The spiritual world of The hobbit,"James S. Bell, James Stuart Bell, Sam O'Neal",2012.0
89,/works/OL23899079W,The Tengwar Hobbit,J.R.R. Tolkien,2020.0
90,/works/OL17554712W,The Unofficial Hobbit Handbook,Jeff Gerke,2012.0
91,/works/OL16704968W,The unofficial Hobbit trivia challenge,Nick Hurwitch,2012.0
92,/works/OL38341864W,The Wisdom of Hobbits,"Matthew J. Distefano, Michael Machuga",2023.0
93,/works/OL22645426W,The World of Hobbits,Paddy Kempshall,2012.0
94,/works/OL10367789W,Tolkien's The Lord of the Rings and The hobbit,Gene B. Hardy,1977.0
95,/works/OL40243911W,Trivia : the Hobbit,Trivion Books,2016.0
96,/works/OL3473990W,Twayne's Masterwork Studies - The Hobbit. A Journey to M...,William H. Green,1994.0
97,/works/OL35867918W,Wholesome Meals from the Hobbit,Johny Bomer,2021.0
98,/works/OL30010020W,William Shakespeare's the Hobbit,Mike Rogers,2019.0
99,/works/OL34160641W,𝕋𝕙𝕖 ℍ𝕠𝕓𝕓𝕚𝕥 Photobook,"Bradford, Rhona Bradford",2022.0

Total records stored: 100