In [1]:
import pandas as pd
import sqlite3

In [2]:
import pandas as pd
import sqlite3

In [3]:
df = pd.read_csv("users.csv")
print("Data from CSV file:")
df

Data from CSV file:

           name                  email   location       phone
0        Ananya       ananya@gmail.com  Mangalore  9876543210
1  Oliver Smith  oliversmith@gmail.com     London  9876543211
2    Priya Nair    priyanair@gmail.com      Kochi  9876543212
3  Kenji Tanaka        kenji@gmail.com      Tokyo  9876543213
4  Mateo Garcia        mateo@gmail.com     Madrid  9876543214

In [4]:
conn = sqlite3.connect("users.db")
cursor = conn.cursor()
print("Database connected!")

Database connected!

In [5]:
cursor.execute("DROP TABLE IF EXISTS users")

cursor.execute("""
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    email TEXT,
    location TEXT,
    phone TEXT
)
""")

conn.commit()
print("Table created!")

Table created!

In [6]:
for index, row in df.iterrows():
    cursor.execute(
        "INSERT INTO users (name, email, location, phone) VALUES (?, ?, ?, ?)",
        (row["name"], row["email"], row["location"], str(row["phone"]))
    )

conn.commit()
print(len(df), "records inserted successfully!")

5 records inserted successfully!

In [7]:
db_data = pd.read_sql_query("SELECT * FROM users", conn)
print("Data from SQLite database:")
db_data

Data from SQLite database:

   id          name                  email   location       phone
0   1        Ananya       ananya@gmail.com  Mangalore  9876543210
1   2  Oliver Smith  oliversmith@gmail.com     London  9876543211
2   3    Priya Nair    priyanair@gmail.com      Kochi  9876543212
3   4  Kenji Tanaka        kenji@gmail.com      Tokyo  9876543213
4   5  Mateo Garcia        mateo@gmail.com     Madrid  9876543214

In [8]:
conn.close()